# Language C++, Ubuntu 18
os: linux
dist: bionic
language: minimal

# Services require docker, docker already contains everything
services:
  - docker

# No recursive limit
git:
  depth: false

# Notifications, no email
notifications:
  email: false

script:
  # pass variables TRAVIS_BRANCH and repo to entry-point
  - docker run -v /home/travis/build/sero-lib/core-utils:/opt/repo -v ~/.ccache:/opt/.ccache yuhanuncitgez/sero_core_utils:latest

cache:
  directories:
    - ~/.ccache